version: '3.8'

services:
  promptfoo_container:
    image: ghcr.io/promptfoo/promptfoo:latest@sha256:19428c20a38db8e07f03f93d8ab16f15e77c11d7bd856c81f0e8907e5e864eae
    ports:
      - 3000:3000
    volumes:
       - promptfoo_data:/home/promptfoo/.promptfoo
    environment:
      - PROMPTFOO_SHARE_CHUNK_SIZE=10
      - OPENAI_API_KEY=${OPENAI_API_KEY}
volumes:
   promptfoo_data:
