version: '3.8'

services:
  promptfoo_container:
    image: ghcr.io/promptfoo/promptfoo:latest
    ports:
      - 3000:3000
    volumes:
       - promptfoo_data:/home/promptfoo/.promptfoo
    environment:
      - PROMPTFOO_SHARE_CHUNK_SIZE=10
      - OPENAI_API_KEY=${OPENAI_API_KEY}
volumes:
   promptfoo_data:
